//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LixPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicLife
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int AcademicType { get; set; }
        public string Academy { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Description { get; set; }
    
        public virtual AcademicType AcademicType1 { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
