//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LixPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hobby
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public string Hoby { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
