//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LixPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int SkillType { get; set; }
        public string Skill1 { get; set; }
        public string Skill_Description { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual SkillType SkillType1 { get; set; }
    }
}
